### ISSUE TITLE
Can the proxy see my information?

### ISSUE THREAD

**Issue by andresespinosapc** [foomo/tlssocks#3]
The information sent through the proxy can be decrypted by the proxy?

**Comment by smartinov** [comment]
@andresespinosapc hi! So, what's happening is that the proxy opens up a tunnel between A (Socks Proxy)  and B (Socks Server).

If you need any additional hops, it does a simple TCP forwarding (like for example if you need to do hops through multiple machines)

So, since the socks5 proxy (which is being used to execute the requests on the target machine), you NEED to ensure that the TCP connection is secure by using certificates between the Socks Proxy & Socks Server.

And given that the target proxy needs to work with the data at the "exit node" which is the Socks Server, it decrypts the data, executes the request, encrypts the data, and sends it back over TLS to the proxy, so that the proxy can return the required data.

I hope I explained it well enough!

**Comment by andresespinosapc** [comment]
Hmm that's the way this package works or it works like that in general? I'm using Node.js's TLS package, I'm sorry to ask here but it's very important to me to understand if the connections is being secure.

I investigated a bit further and the way I think it should work is that the TLS handshake is made directly between the client and the destination server, not with the proxy/socks server. If that's the case, I should be able to check the certificate issued by the destination server and be sure that the TLS handshake was made with it instead of the intermediate proxy server.

As far as I know, after knowing that the server with which I'm making the handshake is the destination server, the secret created by the client can only be decrypted by it, so it shouldn't be possible for the proxy server to decrypt the data sent using TLS.

**Comment by smartinov** [comment]
@andresespinosapc hi! So that's correct. The TLS handshake is not between the client & exit but rather the proxies. That is due to the fact that we have additional authentication on the end as in what username/password is able to access which host from the exit point (Socks Server)

If it's just proxying you're looking for, it's better to use a standard SOCKS proxy. This has additional security in the form of basic authentication per host, so that you can fine-grain access to various services that you wish to expose to the internet.

So security-wise, it's important that you control the entry point to the service as well as the exit point. Everything in between is encrypted. 

So in this use-case, if you're having a private network that isn't full of firewall rules that you can restrict to which hosts is the proxy limited to. This could be only possible if we're able to read the contents of the request from the client, so that we could "replay" it inside the socks server, and return the results to the client.

**Comment by andresespinosapc** [comment]
@smartinov Ok, thank you very much!
